### ISSUE TITLE
Doesn't work with DeluxeMenus

### ISSUE THREAD

**Issue by R13zi** [Daniel-Forge-Development/SpigotPAPIBridge#2]
Everytime i use any placeholder on DeluxeMenus for example %FPAPIBridge_reforged_dex_count% my menu crashes

**Comment by danorris709** [comment]
Crash report?

**Comment by R13zi** [comment]
the server doesn't crash, but the menu that uses any forge placeholder doesn't open.

**Comment by danorris709** [comment]
If you cannot provide some form of error log then I cannot really help you

**Comment by griffindeed** [comment]
Try enable debug mode on Deluxe Menu's main config then reloading. See if it gives more info on reload/trying to open menu?

> the server doesn't crash, but the menu that uses any forge placeholder doesn't open.

> If you cannot provide some form of error log then I cannot really help you

**Comment by R13zi** [comment]
> 

i also can't get the error, I tried in my scoreboard  and i got the same one. Probably is something with the placeholder and not with DeluxeMenus
