### ISSUE TITLE
Doesn't working or i'm dumb?

### ISSUE THREAD

**Issue by joaoszaaa** [Daniel-Forge-Development/SpigotPAPIBridge#3]
After installing everything, i put %FPAPIBridge_reforged_balance% in my scoreboard and... i got this:

%reforged_balance% and yeah... just this

Using: arclight-1.16.5-1.0.24-SNAPSHOT-759a3fd
ReforgedPlaceholders-2.9.1-1.16.5.jar
ForgePlaceholderAPI-Forge-2.0.4-1.16.5.jar
SpigotPAPIBridge-1.0.0.jar
PlaceholderAPI-2.10.5.jar

Everything in the right place...
Spigotpapibridge > Expansion folder
ReforgedPlaceholders > ForgePlaceholderAPI folder

Log: https://pastebin.com/jHptcVTf

**Comment by R13zi** [comment]
Someone on Pixelmon servers told me to use in Pixelmon 1.16.5 the placeholder %FPAPIBridge_reforged16_balance%
